-- MySQL Script generated by MySQL Workbench
-- Mon Dec 19 16:21:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz` DEFAULT CHARACTER SET utf8 ;
USE `quiz` ;

-- -----------------------------------------------------
-- Table `quiz`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `descPerfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(200) NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_User_Perfil1_idx` (`Perfil_idPerfil` ASC),
  CONSTRAINT `fk_User_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `quiz`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Quiz` (
  `idQuiz` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(60) NOT NULL,
  `foto` VARCHAR(200) NULL,
  PRIMARY KEY (`idQuiz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Tema` (
  `idTema` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Quiz_Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Quiz_Tema` (
  `Quiz_idQuiz` INT NOT NULL,
  `Tema_idTema` INT NOT NULL,
  PRIMARY KEY (`Quiz_idQuiz`, `Tema_idTema`),
  INDEX `fk_Quiz_has_Tema_Tema1_idx` (`Tema_idTema` ASC),
  INDEX `fk_Quiz_has_Tema_Quiz_idx` (`Quiz_idQuiz` ASC),
  CONSTRAINT `fk_Quiz_has_Tema_Quiz`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `quiz`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quiz_has_Tema_Tema1`
    FOREIGN KEY (`Tema_idTema`)
    REFERENCES `quiz`.`Tema` (`idTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Pergunta` (
  `idPergunta` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(250) NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  PRIMARY KEY (`idPergunta`),
  INDEX `fk_Pergunta_Quiz1_idx` (`Quiz_idQuiz` ASC),
  CONSTRAINT `fk_Pergunta_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `quiz`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Opcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Opcao` (
  `idOpcao` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(250) NOT NULL,
  `iscorrect` TINYINT NOT NULL,
  `Pergunta_idPergunta` INT NOT NULL,
  PRIMARY KEY (`idOpcao`),
  INDEX `fk_Opcao_Pergunta1_idx` (`Pergunta_idPergunta` ASC),
  CONSTRAINT `fk_Opcao_Pergunta1`
    FOREIGN KEY (`Pergunta_idPergunta`)
    REFERENCES `quiz`.`Pergunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Resposta` (
  `idResposta` INT NOT NULL AUTO_INCREMENT,
  `Opcao_idOpcao` INT NOT NULL,
  `Pergunta_idPergunta` INT NOT NULL,
  PRIMARY KEY (`idResposta`),
  INDEX `fk_Resposta_Opcao1_idx` (`Opcao_idOpcao` ASC),
  INDEX `fk_Resposta_Pergunta1_idx` (`Pergunta_idPergunta` ASC),
  CONSTRAINT `fk_Resposta_Opcao1`
    FOREIGN KEY (`Opcao_idOpcao`)
    REFERENCES `quiz`.`Opcao` (`idOpcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resposta_Pergunta1`
    FOREIGN KEY (`Pergunta_idPergunta`)
    REFERENCES `quiz`.`Pergunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Partida` (
  `idPartida` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `tempo` TIME NOT NULL,
  `n_certas` INT NOT NULL,
  `score` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  PRIMARY KEY (`idPartida`),
  INDEX `fk_Partida_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Partida_Quiz1_idx` (`Quiz_idQuiz` ASC),
  CONSTRAINT `fk_Partida_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `quiz`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `quiz`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`Leaderboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`Leaderboard` (
  `idLeaderboard` INT NOT NULL AUTO_INCREMENT,
  `Partida_idPartida` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  PRIMARY KEY (`idLeaderboard`),
  INDEX `fk_Leaderboard_Partida1_idx` (`Partida_idPartida` ASC),
  INDEX `fk_Leaderboard_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Leaderboard_Quiz1_idx` (`Quiz_idQuiz` ASC),
  CONSTRAINT `fk_Leaderboard_Partida1`
    FOREIGN KEY (`Partida_idPartida`)
    REFERENCES `quiz`.`Partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leaderboard_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `quiz`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leaderboard_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `quiz`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
